version: "3.9"
name: "flaskApp1"
services:
  web:
    build:
      context: ./web  # Path to the directory containing Dockerfile.web
      dockerfile: Dockerfile  # Dockerfile name
    ports:
      - "56733:8000"
    volumes:
      - ./web:/app
    env_file:
      - .env.dev
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
  db:
    image: mongo:latest  # Use the official MongoDB image
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hello_mongo
      - MONGO_INITDB_ROOT_PASSWORD=hello_mongo
      - MONGO_DB=hello_mongo_dev
    volumes:
      - mongodb_data:/data/db  # Mount a volume for MongoDB data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  mongodb_data:
