version: "3.9"
name: "check-grade"
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "56733:8000"
    volumes:
      - ./web:/app
    env_file:
      - .env.dev
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hello_mongo
      - MONGO_INITDB_ROOT_PASSWORD=hello_mongo
      - MONGO_DB=hello_mongo_dev
    volumes:
      - mongodb_data:/data/db
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  mongodb_data:
